### ISSUE TITLE
Move all secrets to the .env file

### ISSUE THREAD

**Issue by ruscaang** [ruscaang/type-content-bot#3]
Now the chat IDs are located right in the repository code. You need to move them to a file with secrets

**Comment by Ekaterina-Sinkova** [comment]
I'll take it

**Comment by Dimildizio** [comment]
refactored main.py for chat_ids.json with chat ids and subtopics however if we want to gitignore the ids we could move them to .env
P.S. sorry, just noticed it had already been taken
