### ISSUE TITLE
Create a database with messages

### ISSUE THREAD

**Issue by ruscaang** [ruscaang/type-content-bot#4]
It is necessary to create a database in which all information about messages would be collected. In the future, this will allow you to create a machine learning model based on marked-up data so that it correctly identifies all types of content. You can save as much information about the message as possible, since there is a lot of useful information in the json that comes from telegram.

**Comment by Ouozen** [comment]
it is best to create and manage a database through sqlalchemy

**Comment by kallebloomkwist** [comment]
@Ouozen I'll try to implement this feature

**Comment by Dimildizio** [comment]
currently in sqlite+aiosqlite however should be adapted\migrated to postgresql+asyncpg
